# Site wide configuration

title:            Wake Up Naveen
locale:           en_US
url:              http://wakeupnaveen.com
description:      In an attempt to wake our chief minister Naveen Patnaik up from his deep slumber I write as the voice of Odisha.

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

#lsi: true
default_asides: [_related.html]
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pradeep Majhi
  avatar: pradeep_prof.jpg
  bio: "Soldier of people daring to challenge the inabilities of a corrupt,ineffective and dull government. Challenging status quo and fighting on the streets for the interest of my people is my full time job. And in my freetime I dream of a motherland where every youth's dreams will be full filled irrespective of their caste, creed , gender and religious beliefs."
  email: iycpradeep@gmail.com
  disccus-shortname: wakeupnaveencom
  facebook-appid: 191465971189480
  twitter: iycpradeep
  facebook: mppradeepmajhi
  google:
    plus: #username
    analytics:
    verify:
    ad-client: ca-pub-6312991114432062
    ad-slot: 6852090037
  bing-verify:
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
twitter:
  username: iycpradeep
  tweet_count: true
  size: normal
  follow_count: false
  tweet_message:       ":title by :username - :url"

facebook:
  app_id:   191465971189480              # For a nicer (no js) sharing experience
  profile_id:                        # For follow button or profile link
  action:              like          # Or recommend
  share:               true         # Also add a share button
  layout:              button        # Choices: standard, box_count, button_count, button
  show_faces:          true
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
